myapp/books/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BookForm(FlaskForm):
  title = StringField('Title', validators=[DataRequired()])
  author = StringField('Author', validators=[DataRequired()])
  summary = TextAreaField('Summary', validators=[DataRequired()])
  submit = SubmitField('Add Book')

myapp/books/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import Book
from myapp.books.forms import BookForm

books = Blueprint('books', __name__)

@books.route('/create', methods=['GET', 'POST'])
@login_required
def add_book():
  form = BookForm()
  if form.validate_on_submit():
    book = Book(title=form.title.data, author=form.author.data, summary=form.summary.data, user_id=current_user.id)
    db.session.add(book)
    db.session.commit()
    flash('Book Added')
    print('Book was added')
    return redirect(url_for('core.index'))
  return render_template('add_book.html', form=form)
  

@books.route('/<int:book_id>')
def book(book_id):
  book = Book.query.get_or_404(book_id) 
  return render_template('book.html', title=book.title, date=book.date, book=book)

@books.route('/<int:book_id>/update', methods=['GET','POST'])
@login_required
def update(book_id):
  book = Book.query.get_or_404(book_id)

  if book.owner != current_user:
    abort(403)

  form = BookForm()

  if form.validate_on_submit():
    book.title = form.title.data
    book.author = form.author.data
    book.summary = form.summary.data
    db.session.commit()
    flash('Book Updated')
    return redirect(url_for('books.add_book',book_id=book.id))

  elif request.method == 'GET':
    form.title.data = book.title
    form.author.data = book.author
    form.summary.data = book.summary

  return render_template('add_book.html',title='Updating',form=form)

@books.route('/<int:book_id>/delete',methods=['GET','POST'])
@login_required
def delete_book(book_id):

    book = Book.query.get_or_404(book_id)
    if book.owner != current_user:
        abort(403)

    db.session.delete(book)
    db.session.commit()
    flash('Book Deleted')
    return redirect(url_for('core.index'))

myapp/core/views.py
from flask import render_template, request, Blueprint
from myapp.models import Book

core = Blueprint('core', __name__)

@core.route('/info')
def index():
  page = request.args.get('page', 1, type=int)
  books = Book.query.order_by(Book.date.desc()).paginate(page=page, per_page=5)
  return render_template('info.html', books=books)

@core.route('/')
def info():
  return render_template('index.html')

myapp/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, Book
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
  form = RegistrationForm()  
  if form.validate_on_submit():
    user = User(email=form.email.data, username=form.username.data, password=form.password.data)
    db.session.add(user)
    db.session.commit()
    flash('Thanks for Registration!')
    return redirect(url_for('users.login'))  
  return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user.check_password(form.password.data) and user is not None:
      login_user(user)
      flash('Log in Success!')
      next = request.args.get('next')
      if next ==None or not next[0]=='/':
          next = url_for('core.info')
      return redirect(next)
  return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.info')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
  form = UpdateUserForm()
  if form.validate_on_submit(): 
    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()
    flash('User account updated!!')
    return redirect(url_for('core.index'))
  elif request.method == 'GET':
    form.username.data = current_user.username
    form.email.data = current_user.email
  return render_template('account.html', form=form)

@users.route('/<username>')
def user_books(username):
  page = request.args.get('page', 1, type=int)
  user = User.query.filter_by(username=username).first_or_404()
  books = Book.query.filter_by(owner=user).order_by(Book.date.desc()).paginate(page=page, per_page=5)
  return render_template('user_books.html', books=books, user=user)

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}
  
<div class="jumbotron">
  <div align="center">
    <h1>Update Your Information</h1>
  </div>
</div>

<div class="container">
  <form method="POST" action="" enctype="multipart/form-data">
    <div class="form-group">
      {{form.hidden_tag()}}
    </div>
    <div class="form-group">
      {{form.username.label(class='form-group')}}<br> 
      {{form.username(class='form-control')}}
    </div>
    <div class="form-group">
      {{form.email.label(class='form-group')}}<br> 
      {{form.email(class='form-control')}}
    </div>

    <div class="submit-btn">
      {{form.submit(class='btn btn-primary')}}
    </div>
  </form>
</div>
{% endblock %}

myapp/templates/add_book.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <form class="form-group" method="POST">
      {{form.hidden_tag()}}

      <div class="form-group">
        {{form.title.label(class="form-control-label")}}<br>
        {{form.title(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
        {{form.author.label(class="form-control-label")}}<br>
        {{form.author(class="form-control form-control-lg")}}
      </div>
        <div class="form-group">
          {{form.summary.label(class="form-control-label")}}<br>
          {{form.summary(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
          {{form.submit(class="btn btn-outline-info")}}
      </div>
    </form>
  </div>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script 
    src="https://kit.fontawesome.com/4da7a940f0.js"
    crossorigin="anonymous"
  ></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <title>BookShelf</title>
</head>
<body>
  <ul class="nav">
    <li class="icon">
      <a class="icon-link" href="{{url_for('core.info')}}"><i class="fas fa-book fa-2x"></i></a>
    <li class="nav-link">
      <a class="navbar-link" href="{{url_for('core.index')}}">Book List</a>
    </li>
    {% if current_user.is_authenticated %}
    <li class="nav-link">
      <a class="navbar-link" href="{{url_for('books.add_book')}}">Add Book</a>
    </li>
    <li class="nav-link">
      <a class="navbar-link" href="{{url_for('users.logout')}}">Log Out</a>
    </li>
    <li class="nav-link">
      <a class="navbar-link" href="{{url_for('users.account')}}">Account</a>
    </li>
    {% else %}
    <li class="nav-link">
      <a class="navbar-link" href="{{url_for('users.login')}}">Log In  </a>
    </li>
    <li class="nav-link">
      <a class="navbar-link" href="{{url_for('users.register')}}">Register</a>
    </li>
    {% endif %}
  </ul>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

myapp/templates/book.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="card">
      <div class="book-car-boy">
        <h1>{{ book.title }} By: {{book.author}}</h1>
        <h2>Summary</h2>
        <h3>{{book.summary}}</h3>
        <p>Added by: {{book.owner.username}}</p>
        <p>Added on: {{ book.date.strftime('%B %d, %Y') }}</p>
        {% if book.owner == current_user %}
          <div class="book-page">
            <a class="btn-primary" href="{{ url_for('books.update', book_id=book.id) }}">Update</a>
            <br>
            <a class="btn-primary" href="{{ url_for('books.delete_book', book_id=book.id) }}" method="POST">Delete</a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Welcome to BookShelf</h1>
    <p>Bookshelf is an app where you can add the books you've read, are reading, or want to read. Go ahead and click <a href="{{url_for('books.add_book')}}">here</a> to add your first novel.</p>
  </div>
{% endblock %}

myapp/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Books</h1>
  </div>
  <div class="container">
    {% for book in books.items %}
      <div class="card">
        <div class="car-boy">
          <h2>
            <a class="card-title" href="{{url_for('books.book', book_id=book.id)}}">{{book.title}} by: {{book.author}}</a>
          </h2>
          <p>Added on: {{book.date.strftime('%Y - %m - %d')}}</p>
          <a class="btn-primary" href="{{url_for('users.user_books', username=book.owner.username)}}">Added by {{book.owner.username}}</a>
          <a class="btn-primary" href="{{url_for('books.book', book_id=book.id)}}">Checkout Book</a>
        </div>
      </div>
    {% endfor %}
  </div>

  <nav class="page-links">
    <ul class="pages">
      {% for page_num in books.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if books.page == page_num %}
        <li class="page-item">
          <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}
  <form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}<br>{{form.email}}<br>
    {{form.password.label}}<br>{{form.password}}<br>
    <div class="submit-btn">
      {{form.submit()}}
    </div>
  </form>
{% endblock %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}

<form method="POST">
  {{form.hidden_tag()}}
  {{form.email.label}}:<br>{{form.email}}<br>
  {{form.username.label}}:<br>{{form.username}}<br>
  {{form.password.label}}:<br>{{form.password}}<br>
  {{form.pass_confirm.label}}:<br>{{form.pass_confirm}}<br>
  <div class="submit-btn">
    {{form.submit()}}
  </div>
</form>
{% endblock %}

myapp/templates/user_books.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>{{user.username}}'s Books</h1>
  </div>
  {% for book in books.items %}
  <div class="container">
    <div class="card">
      <div class ="book-car-boy">
        <h2><a class="card-title" href="{{url_for('books.book', book_id=book.id)}}">{{book.title}} by {{book.author}}</a></h2>
        <h2>Summary:</h2>
        <h3>{{book.summary}}</h3>
        <p>Added By: <a class="btn-primary" href="{{url_for('users.user_books', username=book.owner.username)}}">{{book.owner.username}}</a></p>
        <p>Added On: {{book.date.strftime("%y-%m-%d")}}</p>
      </div>
    </div>
  </div>
  {% endfor %}
  <nav class="page-links">
    <ul class="pages">
      {% for page_num in books.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if books.page == page_num %}
        <li class="page-item">
          <a class="page-link" href="{{url_for('users.user_books', username=user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="{{url_for('users.user_books', username=user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
{% endblock %}